---
bibliography: references.bib
---

# Introduction

## Complexity of Phosphorous

Phosphorous displays a wide range of behaviours in soils, in places where organic, mineral and aqueous phases interface. In phases that contain oxygen Phosphorous is almost exclusively present as several derivates of Orthophosphate $PO_4^{3-}$ It can be found as organic molecules as anhydric- and ester-groups, being needed by all known species as a constituent of DNA and energy transfer-processes. It can be present as anorganic Phosphate either as mono-orthophosphate $PO_4^{3-}$ or poly-orthophosphate $HO-(PO_2)_n-OH$, where it can strongly interact with water, forming, depending on pH $HPO_4^{2-}$ or $H_2PO_4^{-}$. The dissolved species of phosphate are subject to adsorption to clay- and oxide-surfaces of the solid soil-phase, they also form fallout-products such as Apatite, Vivianite etc. With the present metal-cations in the solution. While the solubility constant of most phosphate-salts are comparably low (Wert eingeben), meaning that the fallout and formation of minerals happens at low chemical activities of phosphate, phosphate often is leached from soil-surface-layers, heavily reducing the efficacy of P-fertilization and presenting a disturbance to P-limited ecosystems. Those phenomena, many of them being physicochemically controlled, are influenced by parameters such as pH, ionic-strength, clay-content, specific-surface of the solid phase, amorphous $Fe(OH)_3$-content amorphous $Al(OH)_3$-content, in short the phenomena depend heavily on the composition, distribution and geometry of the soil. Those properties are considered to be stable respectively long-term properties of a soil, when looked at it with the interest of modelling the transport processes of Phosphate in soils. Factors such as water-content, temperature, vegetation and precipitation are factors that temporally can vary fast and to a certain degree unpredictably. Organic forms of phosphates, prominently DNA or oligonucleotides and phytate are also subject to physicochemical reactions, mainly decomposition, but are foremost controlled in their presence by enzymatic processes, where i.e. plants form phytates in seeds to provide the embryo a compact and specific reserve of phosphate, but many bacteria possess via Phytases the ability to hydrolyse phytate and use it for their own means. To assess and cover those phenomena, models, dynamically describing the motion of Phosphorous in soils, differentiate several pools of Phosphorous, most prominently the organic-P, dissolved-P, adsorbed-P, mineral-P, where the difference in temporal behaviour, such as the mean-reside-time invite a differentiation between labile-P, semi-labile-P and so on.

## Principle Mechanism of P-transport to the Plant

Plants that live in ground, interface with their roots the soil-matrix, soil-solution and air-pockets. It is the interface between root and soil-solution, where the exchange, particularly the uptake of water and nutrients happens. High-affinity phosphate transporters are mainly responsible for the transport of phosphate from the soil-solution into the cytosol. The momentary concentration of orthophosphate \[$H_nPO_4^{n-3}$\] in the soil-solution is called the intensity, meaning the $Pi$ that is immediately available to the plant. It is influenced by sinks such as biological uptake, precipitation, adsorption and leaching, sources are dissolution of phosphate-minerals, mineralization resp. enzymatic hydrolization of organic Phosphate-esters and -anhydrides. Since it is difficult and sometimes up to now impossible to accurately assess all these factors, it has been shown beneficial to use a more agnostic approach and regard the diffusion rates, as a black-box model. For the sake of simplicity and feasibility, all biological-uptake can be removed, such that only the interaction between soil-matrix and soil-solution can be observed. Such a model would consist of the soil-matrix, containing the adsorption-surfaces and the interfacing soil-solution that exchanges phosphates until an equilibrium is reached. There have been different approaches to capture the diffusion of Phosphate. The IEK method employs $^{31}P$ and assesses the amount of P, that is exchangeable between both phases and the temporal development of that amount. Flossmann & Richter assessed the net-diffusion rate and equilibrium-concentration, modelling the diffusion-process as a first-order-kinetic. Whilst IEK observes the diffusion in a steady-state, the approach of Flossmann & Richter did start with a system of dried fine soil and deionized water, and subsequently sampling at different time-points, observing the desorption-reaction-speed from start to equilibrium.

## Prediction of biological sinks

The prediction of biological sinks, particularly plant uptake is of great practical and academic interest. To adequately estimate the ability of a soil to provide sufficient $Pi$ by assessing the status of both soil and soil-solution is the basis for economically and ecologically sustainable fertilization practice. Several approaches and models exist and aim to connect estimations of the $Pi$-availability and the expected requirements of crops. The predominant group of models in use try to measure the extractable $Pi$ via different extractants, and depending on agressivity of the extractant to identify different pools of $Pi$. The extraction of $Pi$ with $H_2O$ or weakly extracting aqueous solutions are generally identified as the immediately available $Pi$ or the Intensity. Extractants with strong acids or chelators, able to dissolve and desorb strongly bound $Pi$ are identified as the $Pi$-Pool that will eventually become available to plants and is often called the Capacity. Such models continue to calculate the required amount of $Pi$ by starting with the expexted uptake of the planned crop.

## Current models in the DACH-region

P-models deployed by the VDLUFA as well as GRUD share basic concepts and mathematical form; they will serve as an example how estimations of P-availability from soil tests and fertilization recommendations can be connected. The explained goal of those models is to reach an ecologically adequate level of P-availability such that only the plant-uptake has to be provided via fertilizer and said level can be maintained. Soil tests with nationally different extractants are therefore performed to assess the current P-availability as mentioned above, obtaing different measures of soil-test-phosphorus (STP). Depending on the STP value and the covariates clay-content (sensory measurement) and $C_{org}$-content the tested soil is placed in a P-supply-class ranging from A, depleted to E, eutrophicated. The estimated P-export, meaning the P-uptake of the harvesting organs, obtained by long-term-trials, most often the national mean-value is then adjusted by the affinity of the root-system for P-uptake, notably this is done for only a few major crops, resulting in the uncorrected fertilizer norm. This uncorrected fertilizer norm is subsequently multiplied with the supply-class parameter. This parameter is 1.5 for class A, in order to increase the amount of $Pi$ available, while it is 0 for class E, such that the soil can be depleted to reach class C, designating adequate P-availability. Switzerland currently uses three concurrent STP-methods, with increasing order of extraction strength:

1.  H2010-method: P is extracted using deionized $H_2O$ for 10 minutes
2.  CO2-method: P is extracted using deionized $H_2O$ with 1M $CO_2$ for HOW MANY?? minutes
3.  AAE10-method: P is extracted using edionized $H_2O$ with ????M $NH_4CH_3COO$ and ???? $Na_4EDTA$ for 10 minutes

The three STP-methods shown above notably differed in their amount of isotopically recoverable $Pi$, where P-H2010 and P-CO2 displayed 97% of the $Pi$ extracted being isotopically exchangeably, while AAE10 had below 25% and so did not represent $Pi$ that eventually would become available ([@demaria2005])\
A new approach from the VDLUFA published in 2018 () uses the coefficients obtained from following the approach of Flossmann & Richter and using them as additional information to improve the supply-classification and modifying the correction term to the xpected P-export.

## Requirements to model parameters

Upon close inspection of the models in use, with particular focus on the established and known mode of P-transport, certain requirements have to be met, such that the models can work reliably across different types of soils, crops and weather scenarios. The assessed covariates in particular have to display certain correlations.

-   Since the solubility of $Pi$ in most soil-solutions, interfacing real soils is limited by the presence of metallic cations and adsorptive surfaces typically below 20 ppm per kg soil, plants usually deplete the soil-solution, surrounding the rhizosphere of $Pi$. The intensity of a nutrient must not be changed much or at all, it is to serve as a predictor for a reaction progress and equilibrium. Most of the $Pi$ uptaken by a plant was delivered by a diffusive mass-transport.
-   The covariates used to adjust the fertilization amount, aiming to reach a steady state, where fertilization equals export need to correlate (moderatly strongly) to P-export, P-balance and in cases of low P-levels to the yield of a crop.
-   At least one of the members of the parameter set used must correlate positively with amount of P fertilized, such that it "responds" to the treatment.
-   Given the known mode of transportation of P, being dependend on diffusive mass-transport, the temporal reactivity of the soil-solution to changes in P-concentration, so the P-desorption-kinetic must in some form be present.

In this study soils from the STYCS-trial, under swiss management were used, a modified version of the Flossman & Richter P-desorption-kinetic was used to test, whether the STP-methods P-CO2 and P-AAE10, and the new kinetic model parameters satisfy those requirements, and compare their performance:

## Research Questions

-   I: Is the **method** presented by Flossmann and Richter (1982) with the double extraction **replicable** with the soils from the **STYCS-trial**?
-   II: How do GRUD-measurements of **STP** **correlate** to the soil properties $C_\text{org}$**-content, clay-content, silt-content and pH**?
-   III: Are the kinetic coefficients $k$ **and** $PS$ **correlated to soil properties**?
-   IV: How well can current GRUD methods of **STP** ($P-CO_2$ & $P-AAE10$) **predict** the **Yield-parameters, P-Export and P-Balance**?
-   V: How well can the **kinetic parameters** $k$ & $PS$ **predict Yield-parameters, P-Export and P-Balance**?
