project:
  type: manuscript
  execute-dir: project

# --- Top-level settings ---
bibliography: references.bib
csl: apa.csl

manuscript:
  article: index.qmd
  notebooks:
    # - notebook: notebooks/cars-plot.qmd
    #   title: CarsPlot
    - notebook: notebooks/pretest.qmd
      title: Model Setup
    - notebook: notebooks/coefficient_analysis.qmd
      title: Coefficient Analysis
    - notebook: notebooks/mlr3.qmd
      title: mlr3
    - notebook: notebooks/results.qmd
      title: Preliminary Results
    # - notebook: notebooks/presentation.qmd
    #   title: presentation
  resources:
    # - data/cars.csv
    - presentation/index.html

# --- Format-specific settings ---
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    lof: true
    lot: true
    html-math-method: mathjax
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 250px

  docx:
    toc: true
    toc-depth: 4
    number-sections: true
    lof: true
    lot: true

  # In _quarto.yml, replace your current pdf: block with this one
# In _quarto.yml, replace your current pdf: block with this one

# In _quarto.yml, replace your entire pdf: block with this one
  pdf:
    documentclass: article
    papersize: a4
    pdf-engine: lualatex
    number-sections: true
    mainfont: "Latin Modern Roman"
    sansfont: "Latin Modern Sans"
    monofont: "Latin Modern Mono"
    notebook-links: false
    lof: false
    lot: false
    
    include-in-header:
      - text: |
          \usepackage{graphicx}
          \usepackage{pdfpages}
          \usepackage[a4paper, top=3cm, bottom=3cm, left=3.5cm, right=3.5cm]{geometry}
          \usepackage{fancyhdr}

          % --- Custom Title Page Definition (Robust Version) ---
          \makeatletter
          \renewcommand{\maketitle}{%
            \begin{titlepage}
              \thispagestyle{empty}
              \centering
              
              \vspace*{1cm}
              \includegraphics[width=6cm]{images/eth_logo.png}
              
              \vspace{2cm}
              {\Large Eidgenössische Technische Hochschule Zürich \par}
              {\Large Swiss Federal Institute of Technology Zurich \par}
              
              \vspace{2.5cm}
              {\Large Master's thesis\par}
              \vspace{0.5cm}
              {\large Master's degree programme in Agricultural Sciences\par}
              
              \vfill
              {\huge \bfseries \@title \par}
              
              \vfill
              {\Large \@author \par}
              {\large Student No. 13-938-311 \par}
              
              \vspace{2cm}
              \begin{tabular}{ll}
                \bfseries Supervisor: & Prof. Dr. Emmanuel Frossard \\
                & Institute of Agricultural Sciences, ETH Zurich \\
                \\
                \bfseries Advisor: & Dr. Frank Liebisch \\
                & Water Protection and Substance Flows, Agroscope Reckenholz \\
              \end{tabular}
              
              \vfill
              {\large \@date \par}
            \end{titlepage}
          }
          \makeatother
          % --- End of Custom Title Page Definition ---

          % --- Header Style Definition for Main Document ---
          \fancypagestyle{fancy}{
            \fancyhf{}
            \fancyhead[L]{\nouppercase{\leftmark}}
            \fancyhead[R]{\thepage}
            \renewcommand{\headrulewidth}{0.4pt}
          }

    include-before-body:
      - text: |
          \cleardoublepage
          \tableofcontents
          \cleardoublepage 
          \pagestyle{fancy}
          \pagenumbering{arabic}

    include-after-body:
      - text: |
          \includepdf[pages=-]{declaration.pdf}
