project:  
  type: website
  execute-dir: project

website:
  title: "My Project"
  navbar:
    left:
      - text: "Article"
        href: index.qmd
      - text: "Slides"
        href: presentation.qmd

format:
  html:
    comments:
      hypothesis: true
    math: mathjax
  docx: default
  pdf: default

execute:
  freeze: auto





