project:  
  type: manuscript
  execute-dir: project

# --- Top-level settings ---
bibliography: references.bib
csl: apa.csl
  
manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/pretest.qmd
      title: Model Setup
    - notebook: notebooks/coefficient_analysis.qmd
      title: Coefficient Analysis
    - notebook: notebooks/mlr3.qmd
      title: mlr3
    - notebook: notebooks/results.qmd
      title: Preliminary Results
  resources:
    - presentation/index.html

# --- Format-specific settings ---
format:
  # HTML output settings
  html:
    lof: true
    lot: true
    number-sections: true
    code-fold: true
    comments:
      hypothesis: true
    other-links:
    - text: Presentation
      href: presentation/index.html
    include-in-header:
      - text: |
          <style>
          .quarto-notebook .cell-container .cell-decorator {
            display: none;
          }
          </style>

  # DOCX output settings
  docx:
    number-sections: true
    lof: true
    lot: true

  # PDF output settings
  pdf:
    # --- Basic PDF setup ---
    code-link: false
    documentclass: article
    papersize: a4
    pdf-engine: lualatex # Corrected typo from lualateg
    number-sections: true
    # Use classic LaTeX fonts
    mainfont: "Latin Modern Roman"
    sansfont: "Latin Modern Sans"
    monofont: "Latin Modern Mono"
    
    # --- Add Lists of Figures and Tables ---
    lof: true
    lot: true
    
    # --- Custom LaTeX integration ---
    # 1. Load packages and define metadata for your .sty file
    include-in-header:
      - text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}
          \fancyhead[L]{\nouppercase{\leftmark}}
          \fancyhead[R]{\thepage}
          \renewcommand{\headrulewidth}{0.4pt}
          \usepackage[english,mt]{ethidsc}
          \studentA{Marc Jerónimo Pérez y Ropero}
          \ethidA{13-938-311}
          \emailA{marcpe@ethz.ch}
          \supervision{Prof. Dr. Emmanuel Frossard \\ Dr. Frank Liebisch}
          \declaration
          \infopage

    # 2. Add content at the beginning of the document body
    include-before-body:
      - text: |
          \maketitle
          \tableofcontents

# --- Execution settings ---
execute:
  freeze: true
