project:  
  type: website
  execute-dir: project

website:
  title: "My Project"
  navbar:
    left:
      - text: "Article"
        href: index.qmd
      - text: "Master Thesis Defense"
        href: notebooks/presentation.qmd
      - text: "Model Setup"
        href: notebooks/pretest.qmd
      - text: "Analysis of kinetic parameters and STP"
        href: notebooks/coefficient_analysis.qmd
      - text: "ML-approach to evaluate predictive power STP vs. kinetic parameters"

format:
  html:
    comments:
      hypothesis: false
    embed-resources: true
    code-fold: true
    math: mathjax
  docx: default
  pdf: default

execute:
  freeze: auto





