project:
  type: manuscript
  execute-dir: project

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    math: mathjax
    
  # docx: default
  # jats: default
  # pdf: default

execute:
  freeze: auto



