project:
  type: website
  output-dir: docs
  execute-dir: project

# --- Website Navigation ---
website:
  title: "P-Kinetics"
  navbar:
    left:
      - href: index.html
        text: "Thesis"
      - href: presentation/index.html
        text: "Presentation"
  sidebar:
    - title: "Notebooks"
      style: "docked"
      background: light
      contents:
        - notebooks/pretest.qmd
        - notebooks/coefficient_analysis.qmd
        - notebooks/mlr3.qmd
        - notebooks/results.qmd

# --- Top-level settings ---
bibliography: references.bib
csl: apa.csl

# --- Format-specific settings ---
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    lof: true
    lot: true
    html-math-method: mathjax
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 250px

  docx:
    toc: true
    toc-depth: 4
    number-sections: true
    lof: true
    lot: true

  pdf:
    documentclass: article
    papersize: a4
    pdf-engine: lualatex
    number-sections: true
    mainfont: "Latin Modern Roman"
    sansfont: "Latin Modern Sans"
    monofont: "Latin Modern Mono"
    notebook-links: false
    lof: false
    lot: false
    
    include-in-header:
      - text: |
          \usepackage{graphicx}
          \graphicspath{{./}}
          \usepackage{pdfpages}
          \usepackage[a4paper, top=3cm, bottom=3cm, left=3.5cm, right=3.5cm]{geometry}
          \usepackage{fancyhdr}

          % --- Custom Title Page Definition (Robust Version) ---
          \makeatletter
          \renewcommand{\maketitle}{%
            \begin{titlepage}
              \thispagestyle{empty}
              \centering
              
              \vspace*{1cm}
              \includegraphics[width=6cm]{images/eth_logo.png}
              
              \vspace{2cm}
              {\Large Eidgenössische Technische Hochschule Zürich \par}
              {\Large Swiss Federal Institute of Technology Zurich \par}
              
              \vspace{2.5cm}
              {\Large Master's thesis\par}
              \vspace{0.5cm}
              {\large Master's degree programme in Agricultural Sciences\par}
              
              \vfill
              {\huge \bfseries \@title \par}
              
              \vfill
              {\Large \@author \par}
              {\large Student No. 13-938-311 \par}
              
              \vspace{2cm}
              \begin{tabular}{ll}
                \bfseries Supervisor: & Prof. Dr. Emmanuel Frossard \\
                & Institute of Agricultural Sciences, ETH Zurich \\
                \\
                \bfseries Advisor: & Dr. Frank Liebisch \\
                & Water Protection and Substance Flows, Agroscope Reckenholz \\
              \end{tabular}
              
              \vfill
              {\large \@date \par}
            \end{titlepage}
          }
          \makeatother
          % --- End of Custom Title Page Definition ---

          % --- Header Style Definition for Main Document ---
          \fancypagestyle{fancy}{
            \fancyhf{}
            \fancyhead[L]{\nouppercase{\leftmark}}
            \fancyhead[R]{\thepage}
            \renewcommand{\headrulewidth}{0.4pt}
          }

    include-before-body:
      - text: |
          \cleardoublepage
          \tableofcontents
          \cleardoublepage 
          \pagestyle{fancy}
          \pagenumbering{arabic}

   