project:  
  type: manuscript
  execute-dir: project

# --- Top-level settings ---
bibliography: references.bib
csl: apa.csl
  
manuscript:
  article: index.qmd
  # (Your notebooks and resources here)

# --- Format-specific settings ---
format:
  # (Your html and docx settings here)

  # PDF output settings
  pdf:
    # --- Basic PDF setup ---
    documentclass: article
    papersize: a4
    pdf-engine: lualatex
    number-sections: true
    mainfont: "Latin Modern Roman"
    sansfont: "Latin Modern Sans"
    monofont: "Latin Modern Mono"
    notebook-links: false
    
    # --- Disable auto-generation of LoF/LoT ---
    lof: false
    lot: false
    
    # --- Custom LaTeX integration ---
    # 1. Load packages and DEFINE the header style, but do not apply it yet.
    include-in-header:
      - text: |
          \usepackage{fancyhdr}
          \usepackage[english,mt]{ethidsc}
          % Define the style but don't activate it with \pagestyle{fancy} here
          \fancypagestyle{fancy}{
            \fancyhf{}
            \fancyhead[L]{\nouppercase{\leftmark}}
            \fancyhead[R]{\thepage}
            \renewcommand{\headrulewidth}{0.4pt}
          }
          \studentA{Marc Jerónimo Pérez y Roper}
          \ethidA{13-938-311}
          \emailA{marcpe@ethz.ch}
          \supervision{Prof. Dr. Emmanuel Frossard \\ Dr. Frank Liebisch}
          \declaration
          \infopage

    # 2. Add ToC, then forcefully switch page style and start numbering
    include-before-body:
      - text: |
          \tableofcontents
          \cleardoublepage 
          \pagestyle{fancy}
          \pagenumbering{arabic}

    # 3. Add content at the very end of the document
    include-after-body:
      - text: |
          \newpage
          \phantomsection
          \addcontentsline{toc}{section}{\listfigurename}
          \listoffigures
          \newpage
          \phantomsection
          \addcontentsline{toc}{section}{\listtablename}
          \listoftables

# --- Execution settings ---
execute:
  freeze: true