---
title: "Master Thesis"
author: "Marc Jerónimo Pérez y Ropero"
format: 
  revealjs:
    smaller: true
    scrollable: true
    embed-resources: true
    theme: blood
---


## delete me
```{r}
plot(speed ~ dist, data = cars)
```

## Background

- In my Internship I studied the current GRUD, particularly Mg, P and K 
- Fertilizer requirement models imply $Y\sim STP + Clay$
- Currently only stationery measurement of STP are considered

## Context

- LTE STYCS, all Nutrients equal except P, which is in 6 Levels
- 5 Sites regarded; Cadenazzo, Ellighausen, Rümlang-Altwi, Oensingen, Zürich-Reckenholz


## Variable Introduction

**Soil Variables:**


## Research Questions
- Is the method presented by Flossmann and Richter (1982) with the double extraction replicable with the soils from the STYCS-trial?
predicting relative Yield, P-Export and P-Balance?
- How do GRUD-measurements of STP correlate to the soil properties $C_\text{org}$-content, clay-content, silt-content and pH?
- Are the kinetic coefficients $k$ and $PS$ ($k$ can be interpreted as the relative speed of desorption, $PS$ is the equilibrium concentration of $PO_4^{3-}$ of the observed desorption in the dried fine earth-water suspension 1:20 by weight) correlated to soil properties?
- How well can current GRUD methods of STP ($P-CO_2$ & $P-AAE10$) predict the relative Yield, P-Export and P-Balance?
- Can the kinetic parameters $k$ & $PS$ of the net-release-kinetic of Orthophosphate improve the model power of 

## Breakfast

-   Eat eggs
-   Drink coffee

# In the evening

## Dinner

-   Eat spaghetti
-   Drink wine

## Going to sleep

-   Get in bed
-   Count sheep
